required = ["github.com/dominikschulz/github-releases", "github.com/muesli/goprogressbar"]

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.1"

[[constraint]]
  name = "github.com/dominikschulz/github-releases"
  branch = "master"

[[constraint]]
  name = "github.com/muesli/goprogressbar"
  branch = "master"

[[constraint]]
  name = "github.com/gopasspw/gopass"
  version = "1.8.1"
